### ISSUE TITLE
Внедряется в игру с помощью любого DLL injector-а.

### ISSUE THREAD

**Issue by ilwsm** [r57zone/XInputInjectDLL#1]
> Внедряется в игру с помощью любого DLL injector-а.
Например какого?

**Comment by r57zone** [comment]
Например, такого https://github.com/r57zone/X360Advance/blob/master/README.RU.md#%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D0%BF%D0%B5%D1%80%D0%B2%D1%8B%D0%B9-%D1%81%D0%BF%D0%BE%D1%81%D0%BE%D0%B1-%D1%80%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D1%83%D0%B5%D1%82%D1%81%D1%8F

**Comment by r57zone** [comment]
https://github.com/nefarius/Injector рекомендую этот, сверху по сути обертка над ним

**Comment by ilwsm** [comment]
Спасибо. Но хотел (с/c++) код для реализации в своем проекте.
Нашел вот это - https://github.com/TsudaKageyu/minhook/issues/57
Попробую

**Comment by r57zone** [comment]
Ага, в этом проекте можно код посмотреть https://github.com/nefarius/Injector
